### ISSUE TITLE
StatusBarアイコンの非表示

### ISSUE THREAD

**Issue by uetchy** [kan/cmd-eikana#1]
Karabinerのように、StatusBarアイコンの非表示が出来ると嬉しいです。

**Comment by kan** [comment]
対応検討してみます!

**Comment by kan** [comment]
本家リポジトリのほうにも対応機能が入ったようですね。

このリポジトリではないですが、個人的に開発を始めた同コンセプトのアプリに、このStatusBarアイコンの非表示設定を盛り込ませて頂きました。→ [IMESwitcher](https://github.com/kan/ime-switcher)
